common/models/Brands.php
<?php

namespace common\models;

class Brands extends \common\models\base\BrandsBase
{
    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->setAttribute('created_at', date('Y-m-d H:i:s'));
        }
        $this->setAttribute('updated_at', date('Y-m-d H:i:s'));

        return parent::beforeSave($insert);
    }

    public function rules()
    {
        return [
            [['title', 'parent_category_id', 'sub_category_id'], 'required'],
            [['title', 'parent_category_id'], 'filter', 'filter' => 'trim'],
            [['description'], 'filter', 'filter' => 'trim'],
            [['description'], 'string'],
            [['parent_category_id'], 'integer'],
            [['created_at', 'updated_at', 'is_deleted'], 'safe'],
            [['title'], 'string', 'max' => 255],
            [['parent_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['parent_category_id' => 'id']],
            [['sub_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['sub_category_id' => 'id']],
        ];
    }
}

backend/controllers/BrandsController.php
<?php

namespace backend\controllers;

use backend\components\AdminCoreController;
use common\models\Brands;
use common\models\BrandsSearch;
use common\models\Category;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * BrandsController implements the CRUD actions for Brands model.
 */
class BrandsController extends AdminCoreController
{
    /**
     * {@inheritdoc}
     */
    /*   public function behaviors()
    {
    return [
    'verbs' => [
    'class' => VerbFilter::className(),
    'actions' => [
    'delete' => ['POST'],
    ],
    ],
    ];
    }*/

    /**
     * Lists all Brands models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BrandsSearch();
        //$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $queryParams = array_merge(array(), Yii::$app->request->getQueryParams());
        if (isset($_GET['BrandsSearch']['parent_category_id'])) {
            $amSubCategories = Category::SubCategoryDropdown($_GET['BrandsSearch']['parent_category_id']);
        } else {
            $amSubCategories = Category::SubCategoryDropdown($searchModel->parent_category_id);
        }
        if (isset($_GET['BrandsSearch']['sub_category_id']) && !empty($_GET['BrandsSearch']['sub_category_id'])) {
            $searchModel->sub_category_id = $_GET['BrandsSearch']['sub_category_id'];
        }
        $dataProvider = $searchModel->search($queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'amSubCategories' => $amSubCategories,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Brands model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Brands model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Brands();
        $parentCategories = Category::ParentCategoryDropdown();
        $subCategories = [];
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', Yii::getAlias('@brand_add_message'));
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'parentCategories' => $parentCategories,
            'subCategories' => $subCategories,
        ]);
    }

    /**
     * Updates an existing Brands model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $parentCategories = Category::ParentCategoryDropdown();
        // GET MILESTONES //
        $subCategories = !empty($model->parent_category_id) ? Category::SubCategoryDropdown($model->parent_category_id) : [];
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', Yii::getAlias('@brand_update_message'));
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
            'parentCategories' => $parentCategories,
            'subCategories' => $subCategories,
        ]);
    }

    /**
     * Deletes an existing Brands model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->is_deleted = "1";
        $model->save(false);

        Yii::$app->session->setFlash('success', Yii::getAlias('@brand_delete_message'));
        return $this->redirect(['index']);
    }

    /**
     * Finds the Brands model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Brands the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Brands::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/brands/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Brands */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?=Html::encode($this->title)?></div>
    </div>
    <div class="block-content collapse in">
<div class="brands-form span12 common_search">

    <?php $form = ActiveForm::begin();?>
<div class="row">
                <div class="span3 style_input_width">
    <?=$form->field($model, 'title')->textInput(['maxlength' => true])?>
</div>
</div>
<div class="row">
                <div class="span3 style_input_width">
    <?=$form->field($model, 'description')->textarea(['rows' => 6])?>
</div>
</div>
<div class="row">
                <div class="span3 style_input_width">
    <?=$form->field($model, 'parent_category_id')->dropDownList($parentCategories, [
    'prompt' => Yii::t('app', '-Choose Parent Category-'),
    'onchange' => '
                $.post( "' . Yii::$app->urlManager->createUrl('category/get-subcategory?id=') . '"+$(this).val(), function( data ) {
                  $( "select#brands-sub_category_id" ).html( data );
                });',
]);
?>
</div>
</div>
<div class="row">
                <div class="span3 style_input_width">
 <?=$form->field($model, 'sub_category_id')->dropDownList($subCategories)?>
</div>
</div>
    <div class="form-group">
        <?=Html::submitButton('Save', ['class' => 'btn btn-success'])?>
    </div>

    <?php ActiveForm::end();?>
</div>
</div>
</div>

backend/views/brands/_search.php
<?php

use common\models\Category;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/* @var $this yii\web\View */
/* @var $model common\models\BrandsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="brands-search">

    <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
]);?>
<div class="row">
    <div class="span3 style_input_width">
    <?=$form->field($model, 'title')?>
</div>
</div>
<div class="row">
    <div class="span3 style_input_width">
    <?=$form->field($model, 'description')?>
</div>
</div>
<div class="row">
    <div class="span3 style_input_width">
    <?=$form->field($model, 'parent_category_id')->dropDownList(Category::ParentCategoryDropdown(), [
    'prompt' => Yii::t('app', '-Choose Parent Category-'),
    'onchange' => '
                $.post( "' . Yii::$app->urlManager->createUrl('category/get-subcategory?id=') . '"+$(this).val(), function( data ) {
                  $( "select#brandssearch-sub_category_id" ).html( data );
                });',
]);?>
</div>
</div>
<div class="row">
    <div class="span3 style_input_width">
    <?=$form->field($model, 'sub_category_id')->dropDownList($amSubCategories, [
    'prompt' => Yii::t('app', '-Choose Sub Category-'),
]);?>
</div>
</div>
</div>

    <?php // echo $form->field($model, 'update_at') ?>

     <div class="form-group">
        <?=Html::submitButton('Search', ['class' => 'btn btn-primary'])?>
         <?=Html::a(Yii::t('app', '<i class="icon-refresh"></i> clear'), Yii::$app->urlManager->createUrl(['brands/index', "temp" => "clear"]), ['class' => 'btn btn-default'])?>
    </div>

    <?php ActiveForm::end();?>

</div>

backend/views/brands/create.php
<?php

/* @var $this yii\web\View */
/* @var $model common\models\Brands */

$this->title = 'Create';
$this->params['breadcrumbs'][] = ['label' => 'Manage Brands', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="brands-create email-format-create">

    <?=$this->render('_form', [
    'model' => $model,
    'parentCategories' => $parentCategories,
    'subCategories' => $subCategories,
])?>

</div>

backend/views/brands/index.php
<?php

use common\components\Common;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel common\models\BrandsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Brands';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="brands-index email-format-index">
    <div class="email-format-index">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">Search Here</div>
    </div>
        <div class="block-content collapse in">
        <div class="users-form span12">

     <?=Html::a(Yii::t('app', '<i class="icon-filter icon-white"></i> Filter'), "javascript:void(0);", ['class' => 'btn btn-primary open_search']);?>
     <?php if (!empty($_REQUEST['BrandsSearch']) || (!empty($_GET['temp']) && $_GET['temp'] == "clear")) {?>
        <div class="brands-serach common_search">
         <?php echo $this->render('_search', ['model' => $searchModel, 'amSubCategories' => $amSubCategories]); ?>
        </div>
<?php } else {?>
    <div class="brand-serach common_search">
         <?php echo $this->render('_search', ['model' => $searchModel, 'amSubCategories' => $amSubCategories]); ?>
        </div>
    <?php }?>
</div>
</div>
</div>
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left"><?=Html::encode($this->title)?></div>
        <div class="pull-right">
            <?=Html::a(Yii::t('app', '<i class="icon-plus"></i> Add Brand'), ['create'], ['class' => 'btn btn-success'])?>
            <?=Html::a(Yii::t('app', '<i class="icon-refresh"></i> Reset'), Yii::$app->urlManager->createUrl(['categories/index']), ['class' => 'btn btn-primary'])?>
        </div>
    </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
 <div class="block-content">
        <div class="goodtable">
    <?=GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => null,
    'layout' => "<div class='table-scrollable'>{items}</div>\n<div class='margin-top-10'>{summary}</div>\n<div class='dataTables_paginate paging_bootstrap pagination'>{pager}</div>",
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        // 'id',
        'title',
        'description:ntext',
        [
            'attribute' => 'parent_category_id',
            'value' => function ($data) {
                return !empty($data->parent_category_id) ? $data->parentCategory->title : '-';
            },
        ],
        [
            'attribute' => 'sub_category_id',
            'value' => function ($data) {
                return !empty($data->sub_category_id) ? $data->subCategory->title : '-';
            },
        ],
        //'created_at',
        //'update_at',

        [
            'header' => 'Actions',
            'class' => 'yii\grid\ActionColumn',
            'headerOptions' => ["style" => "width:40%;"],
            'contentOptions' => ["style" => "width:40%;"],
            'template' => '{update}{delete}',
            'buttons' => [
                'update' => function ($url, $model) {
                    $flag = 1;
                    return Common::template_update_button($url, $model, $flag);
                },
                'delete' => function ($url, $model) {
                    $flag = 1;
                    $confirmmessage = "Are you sure you want to delete this Category?";
                    return Common::template_delete_button($url, $model, $confirmmessage, $flag);
                },

            ],
        ],
    ],
]);?>
      </div>
    </div>
</div>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script type="text/javascript">
$( document ).ready(function() {
    $('.brand-serach').hide();
        $('.open_search').click(function(){
            $('.brand-serach').toggle();
        });
    });

</script>

backend/views/brands/update.php
<?php

/* @var $this yii\web\View */
/* @var $model common\models\Brands */

$this->title = 'Update: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Manage Brands', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="brands-update email-format-create">

    <?=$this->render('_form', [
    'model' => $model,
    'parentCategories' => $parentCategories,
    'subCategories' => $subCategories,
])?>

</div>

backend/views/brands/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Brands */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Brands', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="brands-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'description:ntext',
            'category_id',
            'created_at',
            'update_at',
        ],
    ]) ?>

</div>